baseURL = "https://kan-bayashi.github.io/asj-espnet2-tutorial"
languageCode = "ja"
title = "ESPnet2で始めるEnd-to−End音声処理"
theme = "HugoTex"
author = "Tomoki Hayashi"
copyright = "Copyright © 2020, Tomoki Hayashi."

[markup.goldmark.renderer]
unsafe= true
