baseURL = "https://kan-bayashi.github.io/asj-espnet2-tutorial/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "ESPnet2で始めるEnd-to−End音声処理"
theme = "HugoTex"

[author]
name = "Tomoki Hayashi"

[markup.goldmark.renderer]
unsafe= true
